# This workflow automatically update 'Last updated' in README.md when src is modified

name: Update 'Last updated' in README.md
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [install.ps1, src/**, BlockTheSpot.bat]

jobs:
  update-last-updated:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: update 'Last updated' in README.md
        run: sed -ri "s#(<strong>Last updated:</strong> ).*(<br>)#\1$(date +"%d %B %Y")\2#" README.md
        # sed -i "/<strong>Last updated:<\/strong> /s|> .*<br>|> $(date +"%d %B %Y")<br>|" README.md

      - name: Commit and Push README.md
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "[github-actions] update 'Last updated'"
          git push
